services:
  - type: web
    name: telegram-anbot
    env: python
    buildCommand: ""
    startCommand: python anbot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: YOUR_USERNAME
        value: "@canxuanquang"
